config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base

	def to_html
		return unless self.body
		result = self.body
		count = 1
		while contains_stars(result)
			if count % 2 != 0
				result = result.sub('**', '<strong>')
			else
				result = result.sub('**', '</strong>')
			end
			count += 1
		end
		result
	end

	def contains_stars(text)
		text.include? '**'
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def create
		post = Post.new(post_params)
		if post.save
			redirect_to post
		else
			render :new
		end
	end

	private

	def post_params
		params.require(:post).permit(:title, :date, :body)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Starter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.haml
- @posts.each do |post|
	=link_to(post.title, post_path(post))
	%h2= post.date

=link_to("New Post", new_post_path)

app/views/posts/new.haml
= form_for @post do |f|
	Title:
	= f.text_field :title
	Date:
	= f.date_field :date
	Content (markdown accepted):
	= f.text_field :body
	= f.submit "Submit"

app/views/posts/show.haml
%h1= @post.title
%h2= @post.date
%p= @post.to_html.html_safe if @post.body